frog:
  database:
    name: nihongo_lessons

  ftp:
    server: ftpperso.free.fr
    port: 21
    user: xxxxx
    password: xxxxx
    remote-path: /nihongo/lessons

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/${frog.database.name}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

security:
  jwt:
    token:
      signing-key: xxx

logging:
  level:
    root: INFO
    com.frogdevelopment: WARN
    com.frogdevelopment.nihongo: debug
