frog:
  database:
    name: nihongo_lessons

  ftp:
    server: localhost
    port: 2222
    user: frog_admin_user
    password: frog_admin_pwd
    remote-path: lessons/

datasources:
  default:
    url: jdbc:postgresql://localhost:2345/${frog.database.name}?ApplicationName=${micronaut.application.name}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    maximum-pool-size: 5
    minimum-idle: 2
    connection-test-query: SELECT 1

flyway:
  datasources:
    default:
      enabled: true

security:
  jwt:
    token:
      signing-key: xxx

logging:
  level:
    root: INFO
    com.frogdevelopment: WARN
    com.frogdevelopment.nihongo: debug

endpoints:
  all:
    enabled: true
    sensitive: false
    port: 8085
  env:
    enabled: true
  health:
    details-visible: anonymous
    discovery-client:
      enabled: true
