frog:
  database:
    name: nihongo_lessons
  lessons:
    last_ready:
      en_US: 21
      fr_FR: 21
  migrate:
    base-url: http://legall.benoit.free.fr/
    old:
      file-name: nihon_go/NihonGo_All.tsv
      url: http://legall.benoit.free.fr/nihon_go/ + ${frog.migrate.old.file-name}

  ftp:
    hostname: ftpperso.free.fr
    port: 21
    username: XXXX
    password: XXXX
    remote-path: /nihongo/lessons

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/${frog.database.name}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

security:
  jwt:
    token:
      signing-key: xxx

logging:
  level:
    root: INFO
    com.frogdevelopment: WARN
    com.frogdevelopment.nihongo: debug
