micronaut:
  server:
    port: 8091

eureka:
  client:
    defaultZone: http://admin:security_is_fun@localhost:8761
    registration:
      enabled: true

frog:
  database:
    name: nihongo_sentences
  tatoeba:
    url:
      japanese-indices: https://downloads.tatoeba.org/exports/jpn_indices.tar.bz2
      sentences: https://downloads.tatoeba.org/exports/sentences.tar.bz2
      links: https://downloads.tatoeba.org/exports/links.tar.bz2
  ftp:
    server: localhost
    port: 2222
    user: frog_admin_user
    password: frog_admin_pwd
    remote-path: dico/

datasources:
  default:
    url: jdbc:postgresql://localhost:2345/${frog.database.name}?ApplicationName=${micronaut.application.name}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

flyway:
  datasources:
    default:
      enabled: true

logger:
  levels:
    root: INFO
    com.frogdevelopment: WARN
    com.frogdevelopment.nihongo: DEBUG

endpoints:
  all:
    enabled: true
    sensitive: false
  env:
    enabled: true
