frog:
  database:
    name: nihongo_sentences
  tatoeba:
    url:
      japanese-indices: http://downloads.tatoeba.org/exports/jpn_indices.tar.bz2
      sentences: http://downloads.tatoeba.org/exports/sentences.tar.bz2
      links: http://downloads.tatoeba.org/exports/links.tar.bz2

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${frog.database.name}?ApplicationName=${spring.application.name}
    username: ${DB_USER:postgres}
    password: ${DB_PASWORD:postgres}

security:
  jwt:
    token:
      signing-key: xxx
