frog:
  database:
    name: nihongo_entries
  jmdict:
    url: ftp://ftp.monash.edu.au/pub/nihongo/JMdict.gz
  clean: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${frog.database.name}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

  flyway:
    enabled: false

security:
  jwt:
    token:
      signing-key: xxx
logging:
  level:
    root: INFO
    fr.frogdevelopment: INFO
