frog:
  database:
    name: nihongo_entries
  jmdict:
    url: ftp://ftp.monash.edu.au/pub/nihongo/JMdict.gz
  clean: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9173/${frog.database.name}?ApplicationName=${spring.application.name}
    username: frog_admin
    password: ODa9CNfFagOu3YHDRd2YjgkXIyKzUX

security:
  jwt:
    token:
      signing-key: xxx
logging:
  level:
    root: WARN
    fr.frogdevelopment: INFO
