frog:
  database:
    name: nihongo_entries
  jmdict:
    url: ftp://ftp.edrdg.org/pub/Nihongo/JMdict.gz
  clean: false
  ftp:
    hostname: ftpperso.free.fr
    port: 21
    username: XXXXX
    password: XXXXX
    remote-path: /nihongo/dico

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/${frog.database.name}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

  flyway:
    multi-schema: true

security:
  jwt:
    token:
      signing-key: xxx
logging:
  level:
    root: INFO
    com.frogdevelopment: WARN
    com.frogdevelopment.nihongo: debug
